/* ==========================================================================
   Course detail
   ========================================================================== */
function metricBar(label,value,hint){const pct=value==null?0:Math.min(100,(value/5)*100);return '<div><div class="flex items-baseline justify-between"><span class="text-sm font-medium text-foreground">'+label+'</span><span class="font-display text-sm text-muted-foreground">'+(value==null?'–':fmt1(value))+'<span class="text-xs">/5</span></span></div><div class="mt-1.5 h-1.5 w-full overflow-hidden rounded-full bg-secondary"><div class="h-full rounded-full bg-primary transition-all" style="width:'+pct+'%"></div></div><p class="mt-1 text-xs text-muted-foreground">'+hint+'</p></div>'}
function reviewCard(r){return '<article class="rounded-xl border border-border bg-card p-5"><div class="flex flex-wrap items-center justify-between gap-3"><div><p class="font-medium">'+(r.author?esc(r.author):t('course.anonymous_student'))+'</p><p class="text-xs text-muted-foreground">'+t('course.took_it_in',{term:esc(termLabel(r)),date:esc(r.date)})+'</p></div><div class="flex items-center gap-2">'+Stars(r.overall,14)+'<span class="font-display text-lg">'+fmt1(r.overall)+'</span></div></div><p class="mt-3 text-sm leading-relaxed text-foreground/90">'+esc(r.text)+'</p><div class="mt-4 flex flex-wrap gap-4 border-t border-border pt-3 text-xs text-muted-foreground"><span>'+t('course.difficulty_score',{v:r.difficulty})+'</span><span>'+t('course.workload_score',{v:r.workload})+'</span><span>'+t('course.professor_score',{v:r.professor})+'</span></div></article>'}

function renderCourse(id){
  const c=getCourse(id);
  if(!c) return '<main class="mx-auto w-full max-w-5xl px-4 py-10"><a href="#/dashboard" class="inline-flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground">'+ICONS.arrowLeft+' '+t('course.back_to_directory')+'</a><div class="mt-8 rounded-xl border border-dashed border-border p-10 text-center"><p class="text-sm text-muted-foreground">'+t('course.not_found')+'</p><a href="#/dashboard" class="btn btn-primary btn-sm mt-4">'+t('course.back_to_directory_btn')+'</a></div></main>';
  const reviews=reviewsFor(c.id).slice().sort((a,b)=>b.overall-a.overall);const avg=courseAvg(c.id);
  const sidebar=reviews.length?'<div class="space-y-4 border-t border-border pt-5">'+metricBar(t('course.metric_difficulty'),courseMetric(c.id,'difficulty'),t('course.metric_difficulty_hint'))+metricBar(t('course.metric_workload'),courseMetric(c.id,'workload'),t('course.metric_workload_hint'))+metricBar(t('course.metric_professor'),courseMetric(c.id,'professor'),t('course.metric_professor_hint'))+'</div>':'<div class="border-t border-border pt-5"><p class="text-sm text-muted-foreground">'+t('course.be_first_to_review')+'</p></div>';
  return '<main class="mx-auto w-full max-w-5xl px-4 py-10"><a href="#/dashboard" class="inline-flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground">'+ICONS.arrowLeft+' '+t('course.back_to_directory')+'</a>'+
    '<header class="mt-5 flex flex-wrap items-start justify-between gap-6"><div class="max-w-2xl"><p class="font-mono text-xs text-muted-foreground">'+esc(c.code)+' · '+esc(facultyName(c.faculty))+'</p><h1 class="mt-2 font-display text-4xl leading-tight tracking-tight">'+esc(c.title)+'</h1><p class="mt-2 text-muted-foreground">'+esc(c.desc||'')+'</p><p class="mt-3 text-sm text-muted-foreground">'+esc(c.prof)+' · '+c.credits+' credits · '+esc(termsLabel(c.terms))+' · '+esc(enumLabel('level',c.level))+'</p></div>'+
    '<div class="flex flex-wrap gap-2"><button class="btn btn-primary" data-action="write-review">'+ICONS.pen+' '+t('course.write_review')+'</button><button class="btn btn-outline" data-action="report-course">'+ICONS.bug+' '+t('course.report_issue')+'</button></div></header>'+
    '<div class="mt-8 grid gap-6 lg:grid-cols-[320px_1fr]"><aside class="space-y-5 self-start rounded-2xl border border-border bg-card p-5 lg:sticky lg:top-24"><div class="text-center"><p class="font-display text-6xl leading-none">'+(avg==null?'–':fmt1(avg))+'</p>'+Stars(avg,18,'mt-2 justify-center')+'<p class="mt-2 text-xs text-muted-foreground">'+(reviews.length===0?t('course.no_reviews_yet'):tp('course.based_on',reviews.length))+'</p></div>'+sidebar+'</aside>'+
    '<section class="space-y-4"><h2 class="font-display text-2xl">'+t('course.reviews_heading')+'</h2>'+(reviews.length?reviews.map(reviewCard).join(''):'<div class="rounded-xl border border-dashed border-border p-10 text-center"><p class="text-sm text-muted-foreground">'+t('course.no_reviews_for',{code:esc(c.code)})+'</p><button class="btn btn-primary btn-sm mt-4" data-action="write-review">'+t('course.write_first')+'</button></div>')+'</section></div></main>';
}

function bindCourse(){
  $$('[data-action="write-review"]').forEach(b=>b.addEventListener('click',()=>{const id=location.hash.replace('#/courses/','').split('?')[0];if(getCourse(id)) openReviewDialog(id);else toast(t('toast.course_not_found'))}));
  $$('[data-action="report-course"]').forEach(b=>b.addEventListener('click',()=>{const id=location.hash.replace('#/courses/','').split('?')[0];const c=getCourse(id);if(!c) return;openFeedbackDialog({kind:'bug',subject:'Issue with course '+c.code,body:'Course: '+c.code+' — '+c.title+'\n\nDescribe the problem:\n'})}));
}
