/* ==========================================================================
   Profile
   ========================================================================== */
function renderProfile(){
  const mine=inst().reviews.filter(r=>r.authorId===user.id);
  const avgGiven=mine.length?mine.reduce((a,r)=>a+r.overall,0)/mine.length:null;
  const facLabel=user.faculty?facultyName(user.faculty):t('profile.not_specified');
  const list=mine.length?mine.map(r=>{const c=getCourse(r.courseId);return '<article class="rounded-xl border border-border bg-card p-5"><div class="flex flex-wrap items-start justify-between gap-3"><div class="min-w-0"><a href="#/courses/'+r.courseId+'" class="font-medium hover:underline">'+esc(c?c.code+' · '+c.title:'Course')+'</a><p class="mt-0.5 text-xs text-muted-foreground">'+t('course.took_it_in',{term:esc(termLabel(r)),date:esc(r.date)})+' · '+(r.author?t('profile.public'):t('profile.anonymous'))+'</p></div><div class="flex items-center gap-2">'+Stars(r.overall,14)+'<span class="font-display text-lg">'+fmt1(r.overall)+'</span></div></div><p class="mt-3 text-sm leading-relaxed text-foreground/90">'+esc(r.text)+'</p><div class="mt-4 flex flex-wrap items-center justify-between gap-3 border-t border-border pt-3 text-xs text-muted-foreground"><div class="flex flex-wrap gap-4"><span>'+t('course.difficulty_score',{v:r.difficulty})+'</span><span>'+t('course.workload_score',{v:r.workload})+'</span><span>'+t('course.professor_score',{v:r.professor})+'</span></div><div class="flex items-center gap-1"><button class="btn btn-ghost btn-sm" data-edit-review="'+r.id+'"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M13 21h8"/><path d="M21.174 6.812a1 1 0 0 0-3.986-3.987L3.842 16.174a2 2 0 0 0-.5.83l-1.321 4.352a.5.5 0 0 0 .623.622l4.353-1.32a2 2 0 0 0 .83-.497z"/></svg> '+t('profile.edit')+'</button><button class="btn btn-ghost btn-sm btn-danger" data-delete-review="'+r.id+'">'+TRASH+' '+t('profile.delete')+'</button></div></div></article>'}).join(''):'<div class="rounded-xl border border-dashed border-border p-10 text-center"><p class="text-sm text-muted-foreground">'+t('profile.no_reviews_yet')+'</p><a href="#/dashboard" class="btn btn-primary btn-sm mt-4">'+t('profile.find_a_course')+'</a></div>';
  return '<main class="mx-auto w-full max-w-4xl px-4 py-10"><section class="rounded-2xl border border-border bg-card p-6"><div class="flex flex-wrap items-start justify-between gap-4"><div><h1 class="font-display text-3xl tracking-tight">'+esc(user.name)+'</h1><p class="mt-1 text-sm text-muted-foreground">'+esc(user.email)+'</p><p class="mt-1 text-sm text-muted-foreground">'+esc(DB[user.inst].code)+' · '+esc(facLabel)+' · '+esc(user.program)+' · '+esc(user.year)+'</p></div><a href="#/settings" class="btn btn-outline btn-sm">'+t('profile.edit_profile')+'</a></div>'+
    '<div class="mt-6 flex flex-wrap gap-8"><div><p class="font-display text-3xl leading-none">'+mine.length+'</p><p class="mt-1 text-xs uppercase tracking-wider text-muted-foreground">'+t('profile.reviews_written')+'</p></div><div><p class="font-display text-3xl leading-none">'+(avgGiven==null?'–':fmt1(avgGiven))+'</p><p class="mt-1 text-xs uppercase tracking-wider text-muted-foreground">'+t('profile.average_score_given')+'</p></div><div><p class="font-display text-3xl leading-none">'+(user.prefs.anonDefault?t('profile.on'):t('profile.off'))+'</p><p class="mt-1 text-xs uppercase tracking-wider text-muted-foreground">'+t('profile.anon_by_default')+'</p></div></div></section>'+
    '<section class="mt-10"><h2 class="font-display text-2xl">'+t('profile.your_reviews_heading')+'</h2><p class="mt-1 text-sm text-muted-foreground">'+t('profile.your_reviews_subhead')+'</p><div class="mt-4 space-y-3">'+list+'</div></section></main>';
}

function bindProfile(){
  $$('[data-edit-review]').forEach(b=>b.addEventListener('click',()=>openEditReviewDialog(b.dataset.editReview)));
  $$('[data-delete-review]').forEach(b=>b.addEventListener('click',async ()=>{const id=b.dataset.deleteReview;if(!confirm(t('profile.delete_confirm'))) return;try{await db.collection('reviews').doc(id).delete()}catch(error){toast(t('toast.could_not_delete',{error:error.message}));return}await loadUniversity(user.inst);toast(t('toast.review_deleted'));render()}));
}
